### ISSUE TITLE
Add support for controllerAs

### ISSUE THREAD

**Issue by schmitch** [greencatsoft/scalajs-angular#71] opened 2016-01-30 12:27 UTC
It would be great if you guys could add support for controllerAs so that I don't need a scope.

**Comment by mysticfall** [comment] 2016-01-31 09:57
I think it's a duplicate of https://github.com/greencatsoft/scalajs-angular/issues/30. Please continue the discussion in the linked issue, or reopen it if needed. Thanks!

**Closed by mysticfall** 2016-01-31 09:57 UTC
