### ISSUE TITLE
compile error resulting from attaching multiple services to module

### ISSUE THREAD

**Issue by ShengC** [greencatsoft/scalajs-angular#46] opened 2015-07-17 17:59 UTC
I am not even sure if this should be counted as a bug or not.. but from the implementation, it seems to allow this,

    class A extends Controller[Scope] { ... }
    class B extends Controller[Scope] { ... }

    val module = Angular.module("app", Seq.empty)
    //module.controller[A].controller[B] // throws compile error    
    //below compiled
    module.controller[A] 
    module.controller[B]

I have very limited knowledge in macros, but looking at the code, `internal.Angular.controllerFromClass`, after binding a `controller` class to the `module`, returns the `module` itself.

    c.Expr[api.Module](q"{${c.prefix.tree}.module.controller($proxy); ${c.prefix.tree}}")

what am I missing here ?

**Comment by mysticfall** [comment] 2015-07-17 18:43
It's a known problem, about which I briefly mentioned in the README document. I haven't yet spent enough time to get to the bottom of it, but for now, I suspect it to be caused by the following issue:

* https://issues.scala-lang.org/browse/SI-7245

Until it's resolved, I suppose we have to use the more verbose syntax to register multiple services.

**Comment by ShengC** [comment] 2015-07-17 19:14
OK, I was not aware of that..., just a suggestion  -might be better at the language level, just make the controller[A], etc., returns a Unit instead of a Module, so people won't both try that option before it can be fixed :-)

On a separate note, (and bear with me, as I still am trying to get the hang of macros...) 

    ${c.prefix.tree}.module.controller($proxy)

already returns the `Module` as defined in `internal.Module` trait,

    def controller(name: String, constructor: js.Array[js.Any]): Module = js.native

Why returns `${c.prefix.tree}` at the end?

**Comment by mysticfall** [comment] 2015-07-19 15:18
I actually agree with you about explicitly forbidding the method chaining so that it does not confuse users, I just committed the changes. Thanks for the suggestion :)

As to the question, I'm afraid you might have been misled by my ambiguous choice of names.

Even though they have the same name and mostly similar methods, the ```Module``` trait is not the same one with the one in the ```internal``` package. What's returned from the former statement is the internal one, which is a wrapper for the Javascript API, and the one which is returned at the end is a Scala API's counterpart.

I wish I could reuse the same trait between them, but it doesn't seem to be a possible option, due to incompatibilities.

**Comment by ShengC** [comment] 2015-07-19 23:15
Thanks a lot for the explanation. I was lack of interest in macros since I cannot think of a situation I would need to use it in application, but now after reading your code I do think it would be a perfect match for libraries in ScalaJS :-)

Also since the original question is a known issue, please feel free to close this thread.

**Closed** 2015-08-09 07:08 UTC
Labels: bug
